//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaCollection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaCollection.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate Additional Info.
        /// </summary>
        public static string BtnGetProviderData {
            get {
                return ResourceManager.GetString("BtnGetProviderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan For Changes.
        /// </summary>
        public static string BtnRunScanChanges {
            get {
                return ResourceManager.GetString("BtnRunScanChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Changes.
        /// </summary>
        public static string BtnUndo {
            get {
                return ResourceManager.GetString("BtnUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string DeviceAdd {
            get {
                return ResourceManager.GetString("DeviceAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Specific Information.
        /// </summary>
        public static string DeviceData {
            get {
                return ResourceManager.GetString("DeviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of device.
        /// </summary>
        public static string DeviceKind {
            get {
                return ResourceManager.GetString("DeviceKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string Devices_Title {
            get {
                return ResourceManager.GetString("Devices_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dune Player.
        /// </summary>
        public static string DeviceType_Dune {
            get {
                return ResourceManager.GetString("DeviceType_Dune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        public static string DeviceType_PC {
            get {
                return ResourceManager.GetString("DeviceType_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Location.
        /// </summary>
        public static string LocationBaseKind {
            get {
                return ResourceManager.GetString("LocationBaseKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string LocationBaseKind_HTTP {
            get {
                return ResourceManager.GetString("LocationBaseKind_HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string LocationBaseKind_Local {
            get {
                return ResourceManager.GetString("LocationBaseKind_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable HDD.
        /// </summary>
        public static string LocationBaseKind_RemovableHDD {
            get {
                return ResourceManager.GetString("LocationBaseKind_RemovableHDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelf.
        /// </summary>
        public static string LocationBaseKind_Shelf {
            get {
                return ResourceManager.GetString("LocationBaseKind_Shelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string LocationBaseName {
            get {
                return ResourceManager.GetString("LocationBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string LocationBases_Title {
            get {
                return ResourceManager.GetString("LocationBases_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access from Device.
        /// </summary>
        public static string LocationMapping {
            get {
                return ResourceManager.GetString("LocationMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Management.
        /// </summary>
        public static string Locations_Title {
            get {
                return ResourceManager.GetString("Locations_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MissingItemDeleteCheckbox {
            get {
                return ResourceManager.GetString("MissingItemDeleteCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string NewItemAddCheckboxes {
            get {
                return ResourceManager.GetString("NewItemAddCheckboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDB.
        /// </summary>
        public static string TitleExternalResource {
            get {
                return ResourceManager.GetString("TitleExternalResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string TitleLocation {
            get {
                return ResourceManager.GetString("TitleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TitleName {
            get {
                return ResourceManager.GetString("TitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Titles.
        /// </summary>
        public static string Titles_Deleted {
            get {
                return ResourceManager.GetString("Titles_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Titles.
        /// </summary>
        public static string Titles_New {
            get {
                return ResourceManager.GetString("Titles_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        public static string TitleSeries {
            get {
                return ResourceManager.GetString("TitleSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk Update Titles.
        /// </summary>
        public static string UpdateTitles_Title {
            get {
                return ResourceManager.GetString("UpdateTitles_Title", resourceCulture);
            }
        }
    }
}
