//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaCollection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaCollection.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap action_add_16xLG {
            get {
                object obj = ResourceManager.GetObject("action_add_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap action_add_16xMD {
            get {
                object obj = ResourceManager.GetObject("action_add_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_back_color_32xSM {
            get {
                object obj = ResourceManager.GetObject("arrow_back_color_32xSM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_Forward_color_32xSM {
            get {
                object obj = ResourceManager.GetObject("arrow_Forward_color_32xSM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string Audio_TitleKind_Album {
            get {
                return ResourceManager.GetString("Audio_TitleKind_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string Audio_TitleKind_Track {
            get {
                return ResourceManager.GetString("Audio_TitleKind_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap build_Selection_32xLG {
            get {
                object obj = ResourceManager.GetObject("build_Selection_32xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Folder.
        /// </summary>
        internal static string MediaType_AudioFolder {
            get {
                return ResourceManager.GetString("MediaType_AudioFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BluRay Folder.
        /// </summary>
        internal static string MediaType_BluRayFolder {
            get {
                return ResourceManager.GetString("MediaType_BluRayFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BluRay Image.
        /// </summary>
        internal static string MediaType_BluRayImage {
            get {
                return ResourceManager.GetString("MediaType_BluRayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD Image.
        /// </summary>
        internal static string MediaType_CdImage {
            get {
                return ResourceManager.GetString("MediaType_CdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD Folder.
        /// </summary>
        internal static string MediaType_DvdFolder {
            get {
                return ResourceManager.GetString("MediaType_DvdFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD Image.
        /// </summary>
        internal static string MediaType_DvdImage {
            get {
                return ResourceManager.GetString("MediaType_DvdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDDVD Folder.
        /// </summary>
        internal static string MediaType_HddvdFolder {
            get {
                return ResourceManager.GetString("MediaType_HddvdFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDDVD Image.
        /// </summary>
        internal static string MediaType_HddvdImage {
            get {
                return ResourceManager.GetString("MediaType_HddvdImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio File.
        /// </summary>
        internal static string MediaType_MediaFileAudio {
            get {
                return ResourceManager.GetString("MediaType_MediaFileAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video File.
        /// </summary>
        internal static string MediaType_MediaFileVideo {
            get {
                return ResourceManager.GetString("MediaType_MediaFileVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Remove_16xMD {
            get {
                object obj = ResourceManager.GetObject("Remove_16xMD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        internal static string Video_TitleKind_Episode {
            get {
                return ResourceManager.GetString("Video_TitleKind_Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        internal static string Video_TitleKind_Season {
            get {
                return ResourceManager.GetString("Video_TitleKind_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series.
        /// </summary>
        internal static string Video_TitleKind_Series {
            get {
                return ResourceManager.GetString("Video_TitleKind_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Video_TitleKind_Title {
            get {
                return ResourceManager.GetString("Video_TitleKind_Title", resourceCulture);
            }
        }
    }
}
